### ISSUE TITLE
Read default level from the API

### ISSUE THREAD

**Issue by palfrey** [lshift/scrutiny#14]
Need to wait for https://github.com/octokit/octokit.rb/issues/711 to finally complete first, but it's in preview at the moment, so hopefully soon...

**Comment by jayvdb** [comment]
Ping, octokit/octokit.rb#711 is done.

Also related the example file has

```
default-access: <One of pull/push/admin. Whatever the default setting is from https://github.com/organizations/YOUR_ORGANISATION/settings/member_privileges as we can't read it from the API>
```

What if the default level is `none`?  That is my orgs default, and I'm running scrutiny now ...

**Comment by palfrey** [comment]
#20 should fix both the default level and the "none" case
